#ifndef INC_COMPILATION_OPTS_H
#define INC_COMPILATION_OPTS_H

// #define USE_MONITOR_TEST

#define USE_EVENT_CHECK_HEAP 1

// Logging
#define USE_LOGGING
#define LOGGING_ENABLE_TESTS
#define LOGGING_USE_SYSLOG

#define USE_SYSTEM_I2C

#define AUTOCONNECT_PSK "31415926"

/*************************
 *
 * CONFIGs
 *
 *************************/

// Define only one of the following

#define CONFIG_MINIMUM
//#define CONFIG_SUPERVISOR
//#define CONFIG_LED_SPHERE
//#define CONFIG_STEPPER
//#define CONFIG_GPSDO
//#define CONFIG_HEATER

// Modules to be used per config

// All modules, not to be usesd
#ifdef CONFIG_ALL
#define CONFIG_NAME "ALL"
#define USE_REBOOT_DETECTOR
#define USE_MQTT
#define USE_LM75A_TEMP
#define USE_LED
#define USE_HEARTBEAT
#define USE_SPIFFS_EDITOR
#define USE_STEPPER
#define USE_JS
#define USE_UART
#define USE_SIM7000
#define USE_SERVO
#define USE_EEPROM_LFS
#define USE_COMM433
#define USE_PCF8563
#define USE_STWD100
#define USE_INA3221
#define USE_AM2320
#define USE_BUTTON
#define USE_BEEPER
#define USE_LED_INDICATOR
#define USE_BLE
#define USE_ESP32I2C
#define USE_IVAN_SUPERVISOR
#define USE_LED_SPHERE
#define USE_GPSDO
#endif

// Minimum configuration
#ifdef CONFIG_MINIMUM
#define CONFIG_NAME "MINIMUM"
#define USE_REBOOT_DETECTOR
#define USE_HEARTBEAT
#define USE_SPIFFS_EDITOR
//#define USE_EEPROM_LFS
// for testing
//#define USE_LED
//#define USE_LED_INDICATOR
#define USE_BLE
// #define USE_ESP32I2C
#endif

// Supervisor
#ifdef CONFIG_SUPERVISOR
#define CONFIG_NAME "SUPERVISOR"
#define USE_REBOOT_DETECTOR
#define USE_HEARTBEAT
#define USE_SPIFFS_EDITOR
#define USE_UART
#define USE_SIM7000
#define USE_EEPROM_LFS
#define USE_PCF8563
#define USE_STWD100
#define USE_INA3221
#define USE_BUTTON
#define USE_LM75A_TEMP
// #define USE_AM2320
#define USE_ESP32I2C
#define USE_LED_INDICATOR
#define USE_IVAN_SUPERVISOR
#endif

// Led Sphere
#ifdef CONFIG_LED_SPHERE
#define CONFIG_NAME "LED_SPHERE"
#define USE_REBOOT_DETECTOR
#define USE_HEARTBEAT
#define USE_SPIFFS_EDITOR
#define USE_BUTTON
#define USE_BEEPER
#define USE_LED
#define USE_LED_SPHERE
#endif

// Stepper
#ifdef CONFIG_STEPPER
#define CONFIG_NAME "STEPPER"
#define USE_REBOOT_DETECTOR
#define USE_HEARTBEAT
#define USE_SPIFFS_EDITOR
#define USE_STEPPER
#endif

// GPSDO
#ifdef CONFIG_GPSDO
#define CONFIG_NAME "GPSDO"
#define USE_HEARTBEAT
#define USE_SPIFFS_EDITOR
#define USE_MQTT
#define USE_REBOOT_DETECTOR
#define USE_GPSDO
#endif

// HEATER
#ifdef CONFIG_HEATER
#define CONFIG_NAME "HEATER"
#define USE_REBOOT_DETECTOR
#define USE_HEARTBEAT
#define USE_SPIFFS_EDITOR
#define USE_HEATER
#endif


//#define USE_LM75A_TEMP
#define LM75A_TEMP_I2CADDRESS 0x48

// TODO time not implemented yet
//#define USE_TIME
#define TIME_NTP_SERVER "fr.pool.ntp.org"
// for time zone see (https://remotemonitoringsystems.ca/time-zone-abbreviations.php)
#define TIME_TZ_INFO "CET-1CEST-2,M3.5.0/02:00:00,M10.5.0/03:00:00"
#define TIME_USE_DS3231 true

#ifdef USE_LED
#define LED_CONTROLLERS 16
#define LED_PIN_1 4
#define LED_PIN_2 16
#define LED_PIN_3 17
#define LED_PIN_4 18
#define LED_PIN_5 19
#define LED_PIN_6 23
#define LED_PIN_7 22
#define LED_PIN_8 25
#define LED_PIN_9 26
#define LED_PIN_10 27
#endif // USE_LED

#ifdef USE_HEARTBEAT
#define HEARTBEAT_PIN 2
#endif

#ifdef USE_SPIFFS_EDITOR
#define SPIFFS_EDITOR_USER "admin"
#define SPIFFS_EDITOR_PWD "admin"
#endif

#ifdef USE_STEPPER
#define STEPPER_ENABLE_PIN 23
#define STEPPER_M0_PIN 22
#define STEPPER_M1_PIN 21
#define STEPPER_M2_PIN 19
#define STEPPER_RESET_PIN 18
#define STEPPER_SLEEP_PIN 17
#define STEPPER_STEP_PIN 16
#define STEPPER_DIR_PIN 4
#define STEPPER_FAULT_PIN 34
#define STEPPER_STOPPER_PIN 26
#define STEPPER_STOPPER_POWERSENSE_PIN 36
#define STEPPER_LED_PIN 32
#define STEPPER_BUZZER_PIN 33
#define STEPPER_DEBUG_PIN -1

// pins for which to compile suppport in FastLED
#define STEPPER_LED_PIN_1 32
#define STEPPER_LED_PIN_2 33
#define STEPPER_LED_PIN_3 25
#define STEPPER_LED_PIN_4 26
#define STEPPER_LED_PIN_5 27
#define STEPPER_LED_PIN_6 22
#define STEPPER_LED_PIN_7 23
#define STEPPER_LED_PIN_8 4
#define STEPPER_LED_PIN_9 16
#define STEPPER_LED_PIN_10 17
#endif // USE_STEPPER

#ifdef USE_UART
#define UART_TX_PIN 19
#define UART_RX_PIN 21
#endif // USE_UART

#ifdef USE_SIM7000
#ifndef USE_UART
#error "SIM7000 uses UART service, but it was not configured!"
#endif
#define SIM7000_ESP32_SLEEP_PIN 23
#define SIM7000_ESP32_PWRKEY_PIN 22
#endif // USE_SIM7000

#ifdef USE_SERVO
#define SERVO_PIN 33
// LCD pins are defined in platformio.ini
// #define LCD_CLK 18
// #define LCD_MOSI 23
// #define LCD_RES 26
// #define LCD_DC 25
// #define LCD_BLK 32
// #define LCD_MISO 19
// #define LCD_CS1 27
// #define LCD_CS2 17
// #define LCD_PEN 16
#endif

#ifdef USE_EEPROM_LFS
//#define EEPROM_LFS_ENABLE_TESTS
//#define EEPROM_LFS_IN_MEMORY
#endif

#ifdef USE_COMM433
#define COMM433_RX_PIN 25
#define COMM433_TX_PIN 26
#endif

#ifdef USE_GPSDO
// to include test signal generated by PWM
#define GPSDO_GEN
#endif

#endif
